import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={
                    "w-screen h-screen bg-slate-800 font-medium tracking-tight " +
                    inter.className
                }
            >
                {children}
            </body>
        </html>
    );
}
